### ISSUE TITLE
Can not install the quarto filter include-code-files using quarto add

### ISSUE THREAD

**Issue by shafayetShafee** [b3/include-code-files#2]
Hello, I am trying to install this quarto filter in my Windows machine by running the command,

```
quarto add b3/include-code-files
```

But I am getting the following error,

```
Quarto extensions may execute code when documents are rendered. If you do not
trust the authors of the extension, we recommend that you do not install or
use the extension.
 ? Do you trust the authors of this extension (Y/n) » Yes
[>] Downloading
(|) Unzippinginclude-code-files-main/include-code-files.lua: Can't create '\\\\?\\C:\\Users\\User\\AppData\\Local\\Temp\\quarto-session97849a7c\\d153801e\\0cb468cc\\archive\\include-code-files-main\\include-code-files.lua'
tar: Error exit delayed from previous errors.
[>] Unzipping
ERROR: Failed to unzip extension.
include-code-files-main/include-code-files.lua: Can't create '\\\\?\\C:\\Users\\User\\AppData\\Local\\Temp\\quarto-session97849a7c\\d153801e\\0cb468cc\\archive\\include-code-files-main\\include-code-files.lua'
tar: Error exit delayed from previous errors.
```

**Quarto Version**

```
$ quarto --version
1.2.235
```

and using `Windows 10 x64 (build 19044)`

Thanks.

**Comment by b3** [comment]
I am not a Qarto user at all and won't be able to help you. I just wrote the pandoc lua code for the extension, @SamEdwardes wrote the glue needed by Qarto.

Maybe he could help you.

Anyway for what I see from your error it seems to me that Qarto is trying to download a lua file which it treats as an archive file.

**Comment by shafayetShafee** [comment]
Thanks for reaching out. I have worked it out (sort of) by manually downloading the`_extension` folder.

**Comment by drriguz** [comment]
I got the same error when executing the command `quarto add b3/include-code-files@quarto`.

**Comment by drriguz** [comment]
Update: there's https://github.com/quarto-ext/include-code-files now

**Comment by SamEdwardes** [comment]
I will take a look at it this week. 

However, now that the quarto core team is maintaining an extension that does the same thing we should probably recommend users use the extension from the core team instead of this one.

**Comment by b3** [comment]
@SamEdwardes: That will simplify the management of the filter a lot: having a repository for the plain pandoc filter and another for the quarto extension (each with their specific issues). 

You should maybe try to contact @jjallaire in order to include your examples in his repository, if that could be done we should remove them from here and make a notice to redirect quarto users to that quarto repository.

What do you think?

**Comment by SamEdwardes** [comment]
@b3 I completely agree. I "created" this quarto extension before there was an official one from the quarto dev team. Now that the quarto dev team has created and is supporting an extension there is no need for this quarto extension.

I will propose a PR to remove the quarto stuff from this repo.

**Comment by shafayetShafee** [comment]
Since it is decided, I think I should close this issue now. Thanks all of you for looking into the problem 😊.
