### ISSUE TITLE
code-fold: true is not working while using the include-code-files quarto filter 

### ISSUE THREAD

**Issue by shafayetShafee** [b3/include-code-files#3]
While this filter does include codes from an External file, `code-fold: true` or `code-summary: "some text"` is not working for that code chunk (that includes the source code). A quick reproducible example as follows,

**test.py**

```
# code from test.py
for name in ["Sam", "Jake"]:
    print(f"Hello {name}!")

```
**test.qmd**

~~~
---
title: "Including Code"
format:
  html:
    code-fold: true
    code-summary: "Python Code"
jupyter: python3
filters: 
  - include-code-files
---

## Python

```{.python include="test.py"}
```

```{python}
print("Hello World")
```
~~~

**output**

![image](https://user-images.githubusercontent.com/48413872/214519303-a8a14ed2-ee01-4632-84ba-6177f7c95efb.png)

I am using Quarto version,

```
$ quarto --version
1.2.235
```

---

I am also actually having the issue #2 , so I have copied the [`include-code-files`](https://github.com/b3/include-code-files/tree/main/_extensions/include-code-files) folder and put it under a `_extension` directory to use it.

Thanks.

**Comment by b3** [comment]
I am not aware of `code-fold` nor `code-summary` variables in pandoc. I do not see nor of them in the basic [pandoc html5 template](https://github.com/jgm/pandoc-templates/blob/master/default.html5).

It may be something specific to quarto.

Did some of you have any idea where these two variables are defined and used (@shafayetShafee, @SamEdwardes or @jjallaire) so that we try to find a solution to the exposed trouble?

**Comment by b3** [comment]
OK that seem definitively be something specific to quarto as defined in quarto's [doc only](https://quarto.org/docs/output-formats/html-code.html#code-tools).

Any one of you have an idea how this is implemented in quarto? Did they use a specific pandoc template for instance?

**Comment by jjallaire** [comment]
It's implemented as a Lua filter that is built in to Quarto's pipeline: https://github.com/quarto-dev/quarto-cli/blob/main/src/resources/filters/quarto-post/foldcode.lua

**Comment by SamEdwardes** [comment]
Hi @shafayetShafee sorry that it is not working. I would recommend that you use the include code extension that is officially supported the quarto team. I created this extension before that one existed. I am going to propose that we archive this extension in favour of <https://github.com/quarto-ext/include-code-files>.

**Comment by shafayetShafee** [comment]
Hi @SamEdwardes.  No worries 😀. I have actually made an alternative quarto extension [`add-code-files`](https://github.com/shafayetShafee/add-code-files) that works fine with `code-fold`ing.
